---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - template-nad-vlan-cnv-bridge.yaml
  - template-nncp-nic-vlan-br.yaml
  - template-nncp-bond.yaml
