---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nncp-bond
  annotations:
    description: >-
      A NodeNetworkConfigurationPolicy to bond two NICs.

    iconClass: icon-load-balancer
    openshift.io/provider-display-name: Tiger Team
    openshift.io/documentation-url: https://github.com/dlbewley/demo-virt
    openshift.io/support-url: https://github.com/dlbewley/demo-virt/issues
    tags: "networking,nmstate"

objects:
  - apiVersion: nmstate.io/v1
    kind: NodeNetworkConfigurationPolicy
    metadata:
      name: ${BOND}-${NIC1}-${NIC2}
      annotations:
        description: ${DESCRIPTION}
    spec:
      nodeSelector:
        ${NODE_SELECTOR_KEY}: ${NODE_SELECTOR_VALUE}
      desiredState:
        interfaces:

          - name: ${NIC1}
            type: ethernet
            state: up
            mtu: ${MTU}
            ipv4:
              enabled: false
            ipv6:
              enabled: false
          - name: ${NIC2}
            type: ethernet
            state: up
            mtu: ${MTU}
            ipv4:
              enabled: false
            ipv6:
              enabled: false

          - name: ${BOND}
            type: bond
            state: up
            mtu: ${MTU}
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: ${BOND_MODE}
              port:
                - ${NIC1}
                - ${NIC2}



parameters:
  - description: Bond name
    name: BOND
    value: bond0
  - description: Physical NIC 1 to bond
    name: NIC1
    value: ens224
  - description: Physical NIC 2 to bond
    name: NIC2
    value: ens225
  - description: Node Selector Key
    name: NODE_SELECTOR_KEY
    value: node-role.kubernetes.io/worker
  - description: Node Selector Value
    name: NODE_SELECTOR_VALUE
    value: ''
  - description: Bond mode. 802.3ad for LACP, active-backup for failover.
    name: BOND_MODE
    value: 802.3ad
  - description: MTU of interfaces.
    name: MTU
    value: 1500
    required: false
  - description: Policy description
    name: DESCRIPTION
    value: Network Config for adding bond and vlan ${VLAN} and bridge on ${NIC} 
