---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-vgt

resources:
  - ../../base

components:
  # bridge interace
  - ../../components/br-trunk/ovs-bridge
  # network attachment
  - ../../components/trunk/ovs-bridge

patches:

  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
              "machine.openshift.io/cluster-api-machineset": "hub-v4tbg-cnv"
        }
