---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Lab Network 192.168.4.0/24 V1924 via OVS Bridge
  name: vlan-1924-test
  namespace: default
spec:
  # the 'physicalNetworkName' can be reused in other NADs unlike the 'name'
  # this network will be mapped to an appropriate bridge
  # via NNCP in an OVN bridge-mapping
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "vlan-1924-test",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-1924-test",
      "physicalNetworkName": "vmdata-physnet",
      "vlanID": 1924,
      "ipam": {}
    }
