#!/bin/bash

NIC=eth1
VLAN_FRONT=1924

nmcli connection add type vlan con-name $NIC.$VLAN ifname $NIC.$VLAN vlan.parent $NIC vlan.id $VLAN

nmcli connection modify $NIC.$VLAN \
  ipv4.route-metric 200 \
  ipv4.method auto

nmcli connection up $NIC.$VLAN