---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# patches:
#   - path: patch-featuregates.yaml
#     target:
#       group: config.openshift.io
#       version: v1
#       kind: FeatureGate
#       name: cluster

resources:
  - job.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
