---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configure Basics of Homelab network while optionally specifying node selector and NIC name.

resources:
  - ../../base

components:
  - ../../components/vlan-1924/ovs-bridge
  - ../../components/vlan-1926/ovs-bridge
  - ../../components/br-trunk/ovs-bridge
  - ../../components/trunk/ovs-bridge

patches:
  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: br-vmdata
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
              "machine.openshift.io/cluster-api-machineset": "hub-q7dgr-cnv"
        }

      - op: replace
        path: /spec/desiredState/interfaces/0/name
        value: ens224

      - op: replace
        path: /spec/desiredState/interfaces/1/bridge/port/0/name
        value: ens224

  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: ovs-bridge-mapping-1924
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
              "machine.openshift.io/cluster-api-machineset": "hub-q7dgr-cnv"
        }

  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: ovs-bridge-mapping-1926
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
              "machine.openshift.io/cluster-api-machineset": "hub-q7dgr-cnv"
        }

  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: br-trunk
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
              "kubernetes.io/hostname": "NNCP-DISABLED"

        }

