---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

components:
  - ../components/br-vmdata/ovs-bridge
  - ../components/multinetworkpolicy

# enable VLANs in an overlay
#  - ../../components/networks/vlan-1924/ovs-bridge
#  - ../../components/networks/vlan-1926/ovs-bridge

