apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: ip-forward-linux-bridge
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - name: ip-forward-linux-bridge
      data: |
        [main]
        summary=Add IP forwarding to interface hosting linux bridge

        [sysctl]
        # update NIC name as appropriate
        net.ipv4.conf.ens256.forwarding=1
  recommend:
    - profile: ip-forward-linux-bridge
      priority: 10
      match:
        # adjust selector in the overlay kustomization.yaml
        - label: node-role.kubernetes.io/worker
          value: ''