---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalogsource.yaml
  - ../../base

patches:
  - target:
      kind: Subscription
      name: kubevirt-hyperconverged
    path: patch-subscription.yaml
