---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-trunk

labels:
  - includeSelectors: true
    pairs:
      demo: trunk

components:
  # - ../../../networking/components/trunk/ovs-bridge
  - ../../../components/vms/rhel9

resources:
  - namespace.yaml

patches:
  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: ovs-bridge-mapping-trunk
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
              "machine.openshift.io/cluster-api-machineset": "hub-v4tbg-cnv"
        }
      - op: replace
        path: /spec/desiredState/ovn/bridge-mappings/0/bridge
        value: br-vmdata

  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: rhel-node
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/domain/devices/interfaces/-
        value: {
          "name": "nic-trunk",
          "bridge": {},
          "model": "virtio"
        }
      - op: add
        path: /spec/template/spec/networks/-
        value: {
          "name": "nic-trunk",
          "multus": {
            "networkName": "default/trunk"
          }
        }
      - op: replace
        path: /spec/running
        value: true
