---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-vgt

labels:
  - includeSelectors: true
    pairs:
      demo: vgt

components:
  - ../../../components/vms/rhel9

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: demo-vgt
    files:
      - scripts/netsetup
      - scripts/demo

secretGenerator:
  - name: cloudinitdisk-vgt
    files:
      - scripts/userData

resources:
  - namespace.yaml

patches:
  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/domain/devices/interfaces/-
        value: {
          "name": "nic-trunk",
          "bridge": {},
          "model": "virtio"
        }
      - op: add
        path: /spec/template/spec/networks/-
        value: {
          "name": "nic-trunk",
          "multus": {
            "networkName": "demo-vgt/trunk"
          }
        }
      - op: replace
        path: /spec/running
        value: true
      # add volumes for secret and configmap
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud
        value: {
          "secretRef": {
            "name": "cloudinitdisk-vgt"
          }
        }
      - op: add
        path: /spec/template/spec/volumes/-
        value: {
          "name": "demo",
          "configMap": {
            "name": "demo-vgt"
          }
        }
      - op: add
        path: /spec/template/spec/domain/devices/disks/-
        value: {
          "name": "demo",
          "serial": "demo",
          "disk": {
            "bus": "virtio"
          }
        }