---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-mapping-trunk
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - localnet: trunk
          bridge: br-trunk
          state: present 
